TG/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [

 path('register/', UserCreateView.as_view(), name='register'),
 path('register/done', UserCreateDoneView.as_view(), name='register_done'),

]

TG/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),

    path('admin/', admin.site.urls),

    path('reservation/', include('reservation.urls')),

    
]

TG/reservation/urls.py
from django.urls import path, re_path
from reservation.views import *

app_name = 'reservation'

urlpatterns = [
# 가게 목록, 상세정보
 path('', PostListView.as_view(), name='index'),
 path('<int:pk>/', PostDetailView.as_view(), name='detail'),

# 가게 등록, 수정, 삭제
 path('add/', PostCreateView.as_view(), name="add"),
 path('<int:pk>/update/', PostUpdateView.as_view(), name="update"),
 path('<int:pk>/delete/', PostDeleteView.as_view(), name="delete"),

# 예약 등록, 확인
 path('customer/', CustomerListView.as_view(), name='customerindex'),
 path('customer/<int:pk>/', CustomerDetailView.as_view(), name='customerdetail'),

# 예약 하기, 수정, 삭제
 path('customer/add/<int:post_id>', CustomerCreateView.as_view(), name="customeradd"),
 path('customer/<int:pk>/update/', CustomerUpdateView.as_view(), name="customerupdate"),
 path('customer/<int:pk>/delete/', CustomerDeleteView.as_view(), name="customerdelete"),

]

TG/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Eat's Easy</title>

    <!-- 스타일 -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'adminlte/css/adminlte.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% block style %}{% endblock %}

</head>
<body class="hold-transition sidebar-mini">

    <div class="wrapper ">

        {% include "menu.html" %}
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper ml-0">
            <div class="content-header">
                <div class="container-fluid">
                {% block content-header %}{% endblock %}
                </div>
            </div>

            <div class="content">
                <div class="container-fluid">
                {% block content %}{% endblock %}
                </div>
            </div>
        </div>
        {% include "footer.html" %}
    
    <!-- 기본 스크립트 -->
    <script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'adminlte/js/adminlte.min.js' %}"></script>

    {% block script %}{% endblock %}

</body>

</html>
    

TG/templates/footer.html
<!-- Main Footer -->
<footer class="main-footer ml-0">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
        4조 
    </div>
    <!-- Default to the left -->
    <strong>
       Copyright &copy; 2021 <a href="http://127.0.0.1">Eat's Easy</a>. 
    </strong> 
    All rights reserved.
</footer>

TG/templates/home.html
{% extends 'base.html' %}

{% block content-header %}
    <h1 class= 'm-0'>EAT's EASY</h1>
{% endblock  %}

{% block content %}         
    <h3>환영합니다.</h3>
{% endblock  %}

TG/templates/menu.html
<nav class="main-header navbar navbar-expand navbar-white navbar-light ml-0">
    <!-- 좌측 메뉴 그룹 -->
    <ul class="navbar-nav">
       
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'home' %}" class="nav-link">
               <i class="fas fa-home"></i> Home
            </a>

        <li class="nav-item">
                    <a href="{% url 'reservation:index' %}" class="nav-link">
                        <i class="nav-icon fas fa-book"></i>
                        식당 목록
                    </a>
        </li>

    </ul>

    <!-- 우측 메뉴 그룹 -->
    <ul class="navbar-nav ml-auto">

        {% if user.is_active %} 

        <!-- 로그인 상태 -->
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" href="{% url 'password_change' %}">
                <i class="fas fa-user"></i> {{user.username}}
            </a>
        </li>

        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" href={% url 'reservation:customerindex' %}>
                <i class="fas fa-book"></i> 예약 확인/취소
            </a>
        </li>

        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-sign-out-alt"></i> 로그아웃
            </a>
        </li>

      

        {% else %}

         <!-- 로그아웃 상태 -->
        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" href="{% url 'login' %}">
                <i class="fas fa-sign-in-alt"></i> 로그인
            </a>
        </li>

        <li class="nav-item d-none d-sm-inline-block">
            <a class="nav-link" href="{% url 'accounts:register' %}">
                <i class="fas fa-user-plus"></i> 회원가입
            </a>
        </li>

        {% endif %}
    </ul>

</nav>