TG/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from mysite.views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),

    path('admin/', admin.site.urls),

    path('reservation/', include('reservation.urls')),

    
]

TG/reservation/urls.py
from django.urls import path, re_path
from reservation.views import *

app_name = 'reservation'

urlpatterns = [
# 가게 목록, 상세정보
 path('', PostListView.as_view(), name='index'),
 path('<int:pk>/', PostDetailView.as_view(), name='detail'),

# 가게 등록, 수정, 삭제
 path('add/', PostCreateView.as_view(), name="add"),
 path('<int:pk>/update/', PostUpdateView.as_view(), name="update"),
 path('<int:pk>/delete/', PostDeleteView.as_view(), name="delete"),

# 예약 등록, 확인
 path('customer/', CustomerListView.as_view(), name='customerindex'),
 path('customer/<int:pk>/', CustomerDetailView.as_view(), name='customerdetail'),

# 예약 하기, 수정, 삭제
 path('customer/add/<int:post_id>', CustomerCreateView.as_view(), name="customeradd"),
 path('customer/<int:pk>/update/', CustomerUpdateView.as_view(), name="customerupdate"),
 path('customer/<int:pk>/delete/', CustomerDeleteView.as_view(), name="customerdelete"),

]

TG/reservation/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User


class Post(models.Model):
    userid = models.CharField('USERID', max_length=20)
    restaurant_name = models.CharField('우리 가게 이름', max_length=20)
    restaurant_description = models.CharField('가게 설명', max_length=100)
    restaurant_callnumber = models.CharField('가게 전화번호', max_length=13)
    restaurant_address = models.CharField('가게 주소', max_length=100)
    reservation_possible_date = models.DateField('영업 요일')
    reservation_time_begin = models.TimeField('영업 시작하는 시간')
    reservation_time_end = models.TimeField('영업 끝나는 시간')
    reservation_seat = models.IntegerField('예약 가능 좌석 수') 

    owner = models.ForeignKey(User, on_delete=models.CASCADE, 
                                                            verbose_name='OWNER', blank=True, null=True)

    class Meta:
        db_table = 'restaurant_reservations'

    def __str__(self):
        return self.restaurant_name

    def get_absoulte_url(self): # 현재 데이터의 절대 경로 추출
        return reverse('reservation:detail', args=(self.id,))

    def get_previous(self): # 이전 데이터 추출
        return self.get_previous_by_modify_dt()

    def get_next(self): # 다음 데이터 추출
        return self.get_next_by_modify_dt()

    def save(self, *args, **kwargs):
        # 필드 조정 필요시 작성
        super().save(*args, **kwargs)

class Customer(models.Model):
    userid = models.CharField('USERID', max_length=20)
    customer_name = models.CharField('고객 이름', max_length=20)
    customer_callnumber = models.CharField('고객 전화번호', max_length=13)
    customer_reservation = models.BooleanField('예약 여부') 
    customer_reservation_restaurant = models.CharField('예약 식당', max_length=20) 
    customer_reservation_date = models.DateField('예약 날짜')
    customer_reservation_time = models.TimeField('예약 시간')

    owner = models.ForeignKey(User, on_delete=models.CASCADE, 
                                                            verbose_name='OWNER', blank=True, null=True)


    class Meta:
        db_table = 'customer_reservations'

    def __str__(self):
        return self.customer_name

    def get_absoulte_url(self): # 현재 데이터의 절대 경로 추출
        return reverse('#', args=(self.id,))

    def get_previous(self): # 이전 데이터 추출
        return self.get_previous_by_modify_dt()

    def get_next(self): # 다음 데이터 추출
        return self.get_next_by_modify_dt()

    def save(self, *args, **kwargs):
        # 필드 조정 필요시 작성
        super().save(*args, **kwargs)

TG/reservation/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from reservation.models import Post, Customer

from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from accounts.views import OwnerOnlyMixin

###############################################################
# 가게 목록, 가게 상세 정보
###############################################################
class PostListView(ListView):
    model = Post
    template_name = 'reservation/post_all.html'   # 템플릿 파일명 변경
    context_object_name = 'posts'                 # 컨텍스트 객체 이름 변경(object_list)
    paginate_by = 3                               # 페이지네이션, 페이지당 문서 건 수


class PostDetailView(DetailView):
    model = Post

###########################################################################################
# 가게 등록, 수정, 삭제
#########################################################
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields = [
        'restaurant_name', 
        'restaurant_description', 
        'restaurant_callnumber',
        'restaurant_address',
        'reservation_possible_date',
        'reservation_time_begin',
        'reservation_time_end',
        'reservation_seat'      
                       
        ]
    success_url = reverse_lazy('reservation:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class PostUpdateView(OwnerOnlyMixin, UpdateView):
    model = Post
    fields = [
        'restaurant_name', 
        'restaurant_description', 
        'restaurant_callnumber',
        'restaurant_address',
        'reservation_possible_date',
        'reservation_time_begin',
        'reservation_time_end',
        'reservation_seat'      
                       
        ]
    success_url = reverse_lazy('reservation:index')

class PostDeleteView(OwnerOnlyMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('reservation:index')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)



##################################################
#예약 확인, 상세 정보
##################################################

class CustomerListView(ListView):
    model = Customer                 
    template_name = 'reservation/customer_reservation.html'                         

class CustomerDetailView(DetailView):
    model = Customer


##################################################
#예약 하기, 수정하기, 삭제하기
##################################################
class CustomerCreateView(LoginRequiredMixin, CreateView):
    model = Customer
    fields = [

        'customer_name',
        'customer_callnumber',
        'customer_reservation',
        'customer_reservation_restaurant',
        'customer_reservation_date',
        'customer_reservation_time'      
                       
        ]
    success_url = reverse_lazy('reservation:customerindex')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        return context


    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class CustomerUpdateView(OwnerOnlyMixin, UpdateView):
    model = Customer
    fields = [

        'customer_name',
        'customer_callnumber',
        'customer_reservation',
        'customer_reservation_restaurant',
        'customer_reservation_date',
        'customer_reservation_time'      
                       
        ]
    success_url = reverse_lazy('reservation:customerindex')

class CustomerDeleteView(OwnerOnlyMixin, DeleteView):
    model = Customer
    success_url = reverse_lazy('reservation:customerindex')

    def get(self, *args, **kwargs):
        return self.post(*args, **kwargs)

TG/reservation/templates/reservation/customer_detail.html
{% extends "base.html" %}

{% block content-header %}
 <h1>예약 세부 사항</h1>
{% endblock %}

{% block content %}
    
    <div>
    <h3>{{object.customer_name}}</h3>
    </div>

    <div>

    {{object.customer_callnumber}}</br></br>
    {{object.customer_reservation}}</br></br>
    {{object.customer_reservation_restaurant}}</br></br>
    {{object.customer_reservation_date}}</br></br>
    {{object.customer_reservation_time}}</br></br>
      
    </div>
   
    
{% endblock %}

{% comment %} {% block script %}

    <script>
        function deleteCustomer(url) {
        if(!confirm('예약을 취소할까요?')) {
        return
        }
        
        location= url
        }
    </script>

{% endblock %} {% endcomment %}

TG/reservation/templates/reservation/customer_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content-header %}
<h1>가게 예약 하기 - {{user}}</h1>
{% endblock %}

{% block content %}
    <div class=my-5>
        <form action="." method="post" class="form col-sm-8 mx-auto">

        {% csrf_token %}
        {% bootstrap_form form %}

                <button type="submit" class="btn btn-primary">
                <i class="fas fa-check"></i> 확인
                </button>

                <a href="javascript:history.back()" class="btn btn-primary">
                <i class="fas fa-undo"></i> 취소</a> 

        </form>
    </div>
{% endblock %}

TG/reservation/templates/reservation/customer_reservation.html
{% extends 'base.html' %}

{% block content-header %}

<h1> 예약 확인 및 취소</h1>

{% endblock  %}

{% block content %}

<div>
    <h1>고객 예약 확인</h1>
    
    <ul>
    
    {% for customer in object_list %}
       {% if user == customer.owner %}
        <li >
        <a class='bg-primary' href="#">식당이름/ 식당과 연동시켜야함</a>
        <div>
        예약자 ID: {{customer.owner}}</br></br>
        예약자 이름: {{customer.customer_name}}</br></br>
        예약자 전화번호: {{customer.customer_callnumber}}</br></br>
        예약 여부: {{customer.customer_reservation}}</br></br>
        예약 날짜: {{customer.customer_reservation_date}}</br></br>
        예약 시간: {{customer.customer_reservation_time}}</br></br>
        </div>
        </li>

        {% if user == customer.owner %}
        <div>
        <a href="{% url 'reservation:customerupdate' customer.id %}" class="mr-3">
        <i class="far fa-edit"></i> 예약 변경</a>
        
        <a href="{% url 'reservation:customerdelete' customer.id %}" class="text-danger mr-3">
        <i class="fas fa-trash"></i> 예약 취소</a>
        </div>
        {% endif %}
       {%  endif %}
    {% endfor %}
    
    
    </ul>

    

</div>


{% endblock  %}

TG/reservation/templates/reservation/post_all.html
{% extends 'base.html' %}

{% block content-header %}
<h1>식당 목록</h1>
{% endblock %}

{% block content%}

{%for post in posts%}

<div class='col-md-4 bg-warning'>
    <div>
    <h3><a href="{% url 'reservation:detail' post.id %}">{{post.restaurant_name}}</a></h3>
    <p>작성자: {{post.owner}} </p>
    <p>{{post.restaurant_description}}</p>
    <p>{{post.restaurant_callnumber}}</p>
    <p>영업시간: {{post.reservation_time_begin}}~{{post.reservation_time_end}}</p>
    <p>예약 가능 좌석: 0/{{post.reservation_seat}}</p>
    </div>
</div>

{% endfor %}

<div class='text-center'> 
 <span>
 {% if page_obj.has_previous %}
 <a href="?page={{page_obj.previous_page_number}}">Prev</a>
 {% endif %}

 Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages}}
 {% if page_obj.has_next %}
 <a href="?page={{page_obj.next_page_number}}">Next</a>
 {% endif %}
 </span>
</div>

 {% if user.is_active %}
 <div class="text-right mr-3">
 <a href="{%url 'reservation:add'%}" class="btn btn-primary btn-sm">
  우리 가게 등록하기</a>
 </div>
 {% endif %}

{% endblock %}

TG/reservation/templates/reservation/post_detail.html
{% extends 'base.html' %}

{% block content-header %}

<h1>{{object.restaurant_name}}</h1>

{% endblock %}

{% block content%}
<p>
안녕하세요.
</p>

<div>
작성자: {{post.owner}} </br></br>
{{object.restaurant_description}}</br></br>
{{object.restaurant_callnumber}}</br></br>
{{object.restaurant_address}}</br></br>
<p> 영업요일: {{object.reservation_possible_date}}</p>
<p> 영업시간: {{object.reservation_time_begin}} ~ {{object.reservation_time_end}}</p>

<p>-----------------------------------------------------------------</p>

<p>ex)예약 시간 12:00 ~ 13:00//
예약 가능 좌석: 0/{{post.reservation_seat}}</p>
<p>ex)예약 시간 13:00 ~ 14:00//
예약 가능 좌석: 0/{{post.reservation_seat}}</p>
<p>ex)예약 시간 14:00 ~ 15:00//
예약 가능 좌석: 0/{{post.reservation_seat}}</p>
<p>ex)예약 시간 15:00 ~ 16:00//
예약 가능 좌석: 0/{{post.reservation_seat}}</p>
<p>ex)예약 시간 16:00 ~ 17:00//
예약 가능 좌석: 0/{{post.reservation_seat}}</p>
</div>
<div>
{% if user != post.owner and user.is_active%}
<div class='ml-5'>
    <a href="{%url 'reservation:customeradd' post.id%}" class='btn btn-primary btn-sm'>
    <i class='fas fa-book'>예약하기</i>
    </a>
</div>
{% endif %}

<div class='ml-5'>
    <a href='javascript:history.back()' class='btn btn-primary btn-sm'>
    <i class='fas fa-undo'>돌아가기</i>
    </a>
</div>
</div>
{% if user == post.owner %}
<div class="text-right">
 <a href="{% url 'reservation:update' post.id %}" class="mr-3">
 <i class="far fa-edit"></i> 수정</a>
 
 <a href="{% url 'reservation:delete' post.id %}" class="text-danger mr-3">
 <i class="fas fa-trash"></i> 삭제</a>
 </div>
{% endif %}

{% endblock %}

{% comment %} {% block script %}

    <script>
        function deletePost(url) {
        if(!confirm('삭제할까요?')) {
        return
        }
        
        location= url
        }
    </script>

{% endblock %} {% endcomment %}

TG/reservation/templates/reservation/post_form.html
{% extends "base.html" %}
{% load bootstrap4 %}

{% block content-header %}
<h1>우리 가게 등록 - {{user}}</h1>
{% endblock %}

{% block content %}
    <div class=my-5>
        <form action="." method="post" class="form col-sm-8 mx-auto">

        {% csrf_token %}
        {% bootstrap_form form %}

                <button type="submit" class="btn btn-primary">
                <i class="fas fa-check"></i> 확인
                </button>

                <a href="javascript:history.back()" class="btn btn-primary">
                <i class="fas fa-undo"></i> 취소</a> 

        </form>
    </div>
{% endblock %}